valid_Status = [
    'ACTIVE_NOT_RECRUITING',
    'COMPLETED',
    'ENROLLING_BY_INVITATION',
    'NOT_YET_RECRUITING',
    'RECRUITING',
    'SUSPENDED',
    'TERMINATED',
    'WITHDRAWN',
    'AVAILABLE',
    'NO_LONGER_AVAILABLE',
    'TEMPORARILY_NOT_AVAILABLE',
    'APPROVED_FOR_MARKETING',
    'WITHHELD',
    'UNKNOWN'
]

valid_Phase = ['NA', 'EARLY_PHASE1', 'PHASE1', 'PHASE2', 'PHASE3', 'PHASE4']

valid_StudyType = ['EXPANDED_ACCESS', 'INTERVENTIONAL', 'OBSERVATIONAL']

valid_Sex = ['ALL', 'FEMALE', 'MALE']

valid_LocationCountry = [
    'United States',
    'China',
    'France',
    'Canada',
    'Germany',
    'United Kingdom',
    'Spain',
    'Italy',
    'Korea, Republic of',
    'Turkey',
    'Belgium',
    'Netherlands',
    'Egypt',
    'Denmark',
    'Taiwan',
    'Australia',
    'Brazil',
    'Israel',
    'Poland',
    'Switzerland',
    'Sweden',
    'Japan',
    'Austria',
    'Russian Federation',
    'India',
    'Hungary',
    'Norway',
    'Mexico',
    'Czechia',
    'Greece',
    'Argentina',
    'Finland',
    'Hong Kong',
    'Thailand',
    'South Africa',
    'Singapore',
    'Pakistan',
    'Portugal',
    'Romania',
    'Bulgaria',
    'Puerto Rico',
    'Ukraine',
    'New Zealand',
    'Ireland',
    'Chile',
    'Slovakia',
    'Malaysia',
    'Colombia',
    'Czech Republic',
    'Serbia',
    'Croatia',
    'Saudi Arabia',
    'Iran, Islamic Republic of',
    'Lithuania',
    'Philippines',
    'Peru',
    'Indonesia',
    'Estonia',
    'Latvia',
    'Slovenia',
    'Vietnam',
    'Uganda',
    'Kenya',
    'Georgia',
    'Lebanon',
    'Bangladesh',
    'Tunisia',
    'Jordan',
    'Tanzania',
    'United Arab Emirates',
    'Guatemala',
    'Panama',
    'Nigeria',
    'Belarus',
    'Malawi',
    'Nepal',
    'Moldova, Republic of',
    'Zambia',
    'Ethiopia',
    'Bosnia and Herzegovina',
    'Iraq',
    'Ghana',
    'Costa Rica',
    'Cyprus',
    'Dominican Republic',
    'Syrian Arab Republic',
    'Iceland',
    'Qatar',
    'Burkina Faso',
    'Kazakhstan',
    'Zimbabwe',
    'Mali',
    'Ecuador',
    'Kuwait',
    'Venezuela',
    'Luxembourg',
    'Morocco',
    'Congo, The Democratic Republic of the',
    'Cameroon',
    'Mozambique',
    'Cambodia',
    'Rwanda',
    'Senegal',
    'Botswana',
    'Algeria',
    'Sri Lanka',
    'Honduras',
    'Martinique',
    'North Macedonia',
    'Armenia',
    'Oman',
    'Gambia',
    'Monaco',
    'Uruguay',
    "Côte D'Ivoire",
    'Macedonia, The Former Yugoslav Republic of',
    'Paraguay',
    'Réunion',
    'Haiti',
    'Jamaica',
    'Gabon',
    'Bolivia',
    'Guinea-Bissau',
    'Cuba',
    'El Salvador',
    'Guadeloupe',
    'Bahrain',
    'Kyrgyzstan',
    'Sudan',
    'Albania',
    'Malta',
    'Benin',
    'Sierra Leone',
    'Uzbekistan',
    'Former Serbia and Montenegro',
    'Myanmar',
    'Guinea',
    "Lao People's Democratic Republic",
    'Niger',
    'Mongolia',
    'Mauritius',
    'Palestinian Territory, occupied',
    'Congo',
    'Lesotho',
    'Madagascar',
    'French Guiana',
    'Papua New Guinea',
    'Liberia',
    'Guam',
    'Antigua and Barbuda',
    'Trinidad and Tobago',
    'Afghanistan',
    'Kosovo',
    'Swaziland',
    'Montenegro',
    'Belize',
    'Azerbaijan',
    'Bahamas',
    'Nicaragua',
    'Togo',
    'Burundi',
    'Barbados',
    'Fiji',
    'New Caledonia',
    'Chad',
    'Andorra',
    'Angola',
    'Central African Republic',
    'Libyan Arab Jamahiriya',
    'Brunei Darussalam',
    'Liechtenstein',
    'Macau',
    'Mayotte',
    'South Sudan',
    'American Samoa',
    'Grenada',
    'Namibia',
    'Suriname',
    'Virgin Islands (U.S.)',
    'Faroe Islands',
    'Greenland',
    'French Polynesia',
    'Yemen',
    'Bhutan',
    'Comoros',
    'Djibouti',
    'Former Yugoslavia',
    'Saint Kitts and Nevis',
    'Solomon Islands',
    'Somalia',
    'Tajikistan',
    'Equatorial Guinea',
    'Holy See (Vatican City State)',
    'Netherlands Antilles',
    'Palestinian Territories, Occupied',
    'Cayman Islands',
    'Guyana',
    'Jersey',
    'Mauritania',
    'Saint Lucia',
    'Samoa',
    'San Marino',
    'United States Minor Outlying Islands',
    'Vanuatu',
    'Aland Islands',
    'Antarctica',
    'Aruba',
    'Bermuda',
    'Bonaire, Sint Eustatius and Saba',
    'Cape Verde',
    'Dominica',
    'Eritrea',
    'Federated States of Micronesia',
    'Gibraltar',
    'Kiribati',
    'Maldives',
    'Montserrat',
    'Northern Mariana Islands',
    'Saint Martin',
    'Saint Vincent and the Grenadines',
    'Seychelles',
    'Timor-Leste'
]
