from .insights import (
    NSFC_PROJECTS_OVERVIEW_INSIGHTS_PROMPT, 
    NSFC_PROJECTS_MECHANISM_INSIGHTS_PROMPT, 
    NSFC_PROJECTS_INSIGHTS_PROMPT,
    PUBMED_RECORDS_OVERVIEW_INSIGHTS_PROMPT,
)
from .brief import YANJIU_XIANZHUANG_BRIEF_PROMPT
from .blueprints import NSFC_PROJECT_BLUEPRINTS_NO_DOCS_PROMPT, NSFC_PROJECT_BLUEPRINTS_WITH_DOCS_PROMPT
from .outline import NSFC_PROPOSAL_OUTLINE_PROMPT
from .writing import (
    LIXIANG_YIJU_PROMPT, 
    LIXIANG_YIJU_OTHER_PARTS_PROMPT, 
    YANJIU_JICHU_PROMPT, 
    QITA_SHUOMING_PROMPT, 
    YANJIU_YIYI_PROMPT, 
    YANJIU_XIANZHUANG_PROMPT,
    YANJIU_JIHUA_PROMPT,
    YUQI_CHENGGUO_PROMPT,
    KEXINGXING_NO_DOCS_PROMPT,
    KEXINGXING_WITH_DOCS_PROMPT,
    YANJIU_FANGAN_PROMPT,
    JISHU_LUXIAN_PROMPT,
    GUANJIAN_JISHU_PROMPT,
    YANJIU_MUBIAO_PROMPT,
    YANJIU_NEIRONG_PROMPT,
    KEXUE_WENTI_PROMPT,
    CHUANGXINXING_PROMPT,
    YANJIU_JICHU_WITH_USER_DOCS_PROMPT,
    YANJIU_JICHU_WITHOUT_USER_DOCS_PROMPT,
    GONGZUO_TIAOJIAN_PROMPT,
    KEYAN_XIANGMU_QINGKUANG_PROMPT,
    NSFC_PROJECTS_QINGKUANG_PROMPT
)

__all__ = [
    "YANJIU_XIANZHUANG_BRIEF_PROMPT",
    "NSFC_PROJECTS_OVERVIEW_INSIGHTS_PROMPT",
    "NSFC_PROJECTS_MECHANISM_INSIGHTS_PROMPT",
    "NSFC_PROJECTS_INSIGHTS_PROMPT",
    "PUBMED_RECORDS_OVERVIEW_INSIGHTS_PROMPT",
    "NSFC_PROJECT_BLUEPRINTS_NO_DOCS_PROMPT",
    "NSFC_PROJECT_BLUEPRINTS_WITH_DOCS_PROMPT",
    "NSFC_PROPOSAL_OUTLINE_PROMPT",
    "LIXIANG_YIJU_PROMPT",
    "LIXIANG_YIJU_OTHER_PARTS_PROMPT",
    "YANJIU_YIYI_PROMPT",
    "YANJIU_XIANZHUANG_PROMPT",
    "YANJIU_JICHU_PROMPT",
    "QITA_SHUOMING_PROMPT",
    "YANJIU_JIHUA_PROMPT",
    "YUQI_CHENGGUO_PROMPT",
    "KEXINGXING_NO_DOCS_PROMPT",
    "KEXINGXING_WITH_DOCS_PROMPT",
    "YANJIU_FANGAN_PROMPT",
    "JISHU_LUXIAN_PROMPT",
    "GUANJIAN_JISHU_PROMPT",
    "YANJIU_MUBIAO_PROMPT",
    "YANJIU_NEIRONG_PROMPT",
    "KEXUE_WENTI_PROMPT",
    "CHUANGXINXING_PROMPT",
    "YANJIU_JICHU_WITH_USER_DOCS_PROMPT",
    "YANJIU_JICHU_WITHOUT_USER_DOCS_PROMPT",
    "GONGZUO_TIAOJIAN_PROMPT",
    "KEYAN_XIANGMU_QINGKUANG_PROMPT",
    "NSFC_PROJECTS_QINGKUANG_PROMPT"
]


